
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SGR
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com:
      example:
        orderserver:
          dao: debug


##超时配置方式一
##服务间调用超时设置，不设置默认是1s。
#ribbon:
##  配置连接超时时间
#  ConnectTimeout: 5000
##  配置业务等待超时时间
#  ReadTimeout: 5000

#超时配置方式2
feign:
  client:
    config:
      PRODUCT-SERVER:
        ConnectTimeout: 2000
        ReadTimeout: 2000
#开启hystrix（服务熔断）
  hystrix:
    enabled: true

#负载均衡
#com.netflix.loadbalancer.RandomRule 随机
#com.netflix.loadbalancer.RoundRobinRule 轮询
#com.netflix.loadbalancer.RetryRule 重试
#com.netflix.loadbalancer.WeightedResponseTimeRule 配置规则 响应时间权重
#com.netflix.loadbalancer.BestAvailableRule 配置规则 最空闲连接策略
PRODUCT-SERVER:
  ribbon:
#    轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


