#服务端口
server:
  port: 8081

#  服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        远程配置文件地址（GitHub仓库地址）
        git:
          uri: https://gitee.com/stone-soil/config-file.git
          username: shiguorang@163.com
          password: 0478521SGR520
#          默认拉取的分支
          default-label: dev
#          拉取文件后的存储地址
          basedir: F:\javaProject\agriculture-server\config-server\src\main\resources\gitfile


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

