#服务端口
server:
  port: 8081

#  服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        远程配置文件地址（GitHub仓库地址）
        git:
          uri: https://github.com/747Sgr/springcloudconfig.git


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

